/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package practice;

import static practice.PascalTriangle.pr;
import static practice.PascalTriangle.prln;

/**
 *
 * @author Nayeem
 */
public class NewJFrame extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    public NewJFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnPassTri = new javax.swing.JButton();
        txtPasTriInput = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtShow = new javax.swing.JTextPane();

        btnPassTri.setBackground(new java.awt.Color(153, 255, 153));
        btnPassTri.setText("Pascal Triangle");
        btnPassTri.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPassTriActionPerformed(evt);
            }
        });

        jScrollPane1.setViewportView(txtShow);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(txtPasTriInput, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(btnPassTri, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 660, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtPasTriInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnPassTri))
                .addGap(87, 87, 87)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnPassTriActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPassTriActionPerformed
        PascalTriangle pasTri = new PascalTriangle();
        
        
        pascalTriangle(Integer.parseInt(txtPasTriInput.getText()));
        
        //
    }//GEN-LAST:event_btnPassTriActionPerformed

    public void pascalTriangle(int treeLength) {
        String valueToShow = "";
        int[][] pascal = new int[treeLength][treeLength];

        //for assign value for colum 0 & row 0
        for (int i = 0; i < treeLength; i++) {
            pascal[0][i] = 1;
            pascal[i][0] = 1;
        }

        //for assaign value
        for (int row = 1; row < treeLength; row++) {
            for (int column = 1; column < treeLength-row; column++) {
                pascal[row][column] = pascal[row][column - 1] + pascal[row - 1][column];
            }
        }

        //for print assaign value
        for (int row = 0; row < treeLength; row++) {
            for (int column = 0; column < treeLength-row; column++) {
                valueToShow += Integer.toString(pascal[row][column]) + "\t";
            }
            valueToShow +="\n";
        }
         txtShow.setText(valueToShow);
    }
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnPassTri;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField txtPasTriInput;
    private javax.swing.JTextPane txtShow;
    // End of variables declaration//GEN-END:variables
}
