package com.gov.npi.lms.view;

import com.gov.npi.lms.domain.BookSummary;
import com.gov.npi.lms.navigation.NavigationMenu;
import com.gov.npi.lms.service.BookIssueReturnService;
import com.gov.npi.lms.service.BookSummaryService;
import java.awt.Toolkit;
import java.util.List;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Samrat Al Shahriar
 */
public class BookSummaryForm extends javax.swing.JFrame {

    /**
     * Creates new form BookSummaryForm
     */
    public BookSummaryForm() {
        initComponents();
        this.setExtendedState(MAXIMIZED_BOTH);
        setJMenuBar(NavigationMenu.commonNavMenu(this));
        refreshTable();
        setAppIcon();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroupSearch = new javax.swing.ButtonGroup();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        rdbBookID = new javax.swing.JRadioButton();
        rdbBookName = new javax.swing.JRadioButton();
        txtSearch = new javax.swing.JTextField();
        btnSearch = new javax.swing.JButton();
        lblMsgSearch = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblDisplay = new javax.swing.JTable();
        jMenuBar1 = new javax.swing.JMenuBar();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Book Summary || LMS");
        setBackground(new java.awt.Color(255, 153, 204));

        jPanel2.setBackground(new java.awt.Color(0, 153, 51));

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 26)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(102, 255, 0));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Book Summary");

        jLabel17.setBackground(new java.awt.Color(0, 204, 204));
        jLabel17.setFont(new java.awt.Font("Monotype Corsiva", 1, 14)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(0, 255, 204));
        jLabel17.setText("Library Management System");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel17)
                .addGap(0, 651, Short.MAX_VALUE))
            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel17)
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addContainerGap(33, Short.MAX_VALUE))
        );

        jPanel3.setBackground(new java.awt.Color(102, 102, 102));

        jLabel4.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel4.setText("Search By-");

        buttonGroupSearch.add(rdbBookID);
        rdbBookID.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        rdbBookID.setText("Accession No");

        buttonGroupSearch.add(rdbBookName);
        rdbBookName.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        rdbBookName.setText("Book Title");

        btnSearch.setBackground(new java.awt.Color(153, 153, 153));
        btnSearch.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/gov/npi/lms/images/lms-search-icon.png"))); // NOI18N
        btnSearch.setText("Search ");
        btnSearch.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnSearch.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        btnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchActionPerformed(evt);
            }
        });

        lblMsgSearch.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(lblMsgSearch, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap(521, Short.MAX_VALUE)
                        .addComponent(jLabel4)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtSearch, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(rdbBookID)
                                .addGap(18, 18, 18)
                                .addComponent(rdbBookName)))))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(rdbBookID)
                        .addComponent(rdbBookName)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblMsgSearch, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSearch, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        tblDisplay.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Accession No", "Book Title", "Total Stock", "Aready Lend", "Now Available", "Lost Quantity"
            }
        ));
        jScrollPane1.setViewportView(tblDisplay);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jScrollPane1)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 257, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
        try {
            if (buttonGroupSearch.getSelection() != null) {
                if (rdbBookID.isSelected()) {
                    lblMsgSearch.setText("");
                    BookIssueReturnService bookIssRetSer = new BookIssueReturnService();
                    BookSummaryService bookSummaryService = new BookSummaryService();
                    List<BookSummary> pList = bookSummaryService.getListByBookID(txtSearch.getText());
                    DefaultTableModel model = (DefaultTableModel) tblDisplay.getModel();
                    model.setRowCount(0);
                    Object[] row = new Object[6];

                    for (int i = 0; i < pList.size(); i++) {
                        //row[0] = pList.get(i).getId();
                        row[0] = pList.get(i).getBookId();
                        row[1] = pList.get(i).getBookName();
                        row[2] = pList.get(i).getTotalStock();
                        row[3] = pList.get(i).getAlreadyLend();
                        row[4] = pList.get(i).getAvilableStock();
                        row[5] = pList.get(i).getLostQuantity();

                        model.addRow(row);
                    }

                } else if (rdbBookName.isSelected()) {
                     lblMsgSearch.setText("");
                    BookIssueReturnService bookIssRetSer = new BookIssueReturnService();
                    BookSummaryService bookSummaryService = new BookSummaryService();
                    List<BookSummary> pList = bookSummaryService.getListByBookName(txtSearch.getText());
                    DefaultTableModel model = (DefaultTableModel) tblDisplay.getModel();
                    model.setRowCount(0);
                    Object[] row = new Object[6];

                    for (int i = 0; i < pList.size(); i++) {
                        //row[0] = pList.get(i).getId();
                        row[0] = pList.get(i).getBookId();
                        row[1] = pList.get(i).getBookName();
                        row[2] = pList.get(i).getTotalStock();
                        row[3] = pList.get(i).getAlreadyLend();
                        row[4] = pList.get(i).getAvilableStock();
                        row[5] = pList.get(i).getLostQuantity();

                        model.addRow(row);
                    }
                } else {
                    lblMsgSearch.setText("Please Select \'Accession No\' or \'Book Title\'");
                }
            } else {
                lblMsgSearch.setText("*Please Select \'Accession No\' or \'Book Title\'");
            }
        } catch (Exception e) {
            String rdbSearch = null;
            if (rdbBookID.isSelected()) {
                rdbSearch = " Accession No";
            } else if (rdbBookName.isSelected()) {
                rdbSearch = "Book Title";
            }
        }
    }//GEN-LAST:event_btnSearchActionPerformed

    public void displayDatasWithinTable() {
        BookSummaryService bookSummaryService = new BookSummaryService();
        List<BookSummary> pList = bookSummaryService.getList();
        DefaultTableModel model = (DefaultTableModel) tblDisplay.getModel();
        Object[] row = new Object[6];

        for (int i = 0; i < pList.size(); i++) {
            //row[0] = pList.get(i).getId();
            row[0] = pList.get(i).getBookId();
            row[1] = pList.get(i).getBookName();
            row[2] = pList.get(i).getTotalStock();
            row[3] = pList.get(i).getAlreadyLend();
            row[4] = pList.get(i).getAvilableStock();
            row[5] = pList.get(i).getLostQuantity();

            model.addRow(row);
        }

    }

    public void refreshTable() {
        DefaultTableModel model = (DefaultTableModel) tblDisplay.getModel();
        model.setRowCount(0);
        displayDatasWithinTable();
    }
    
    public void setAppIcon() {
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/com/gov/npi/lms/images/lms-icon.png")));
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BookSummaryForm.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BookSummaryForm.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BookSummaryForm.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BookSummaryForm.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BookSummaryForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSearch;
    private javax.swing.ButtonGroup buttonGroupSearch;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblMsgSearch;
    private javax.swing.JRadioButton rdbBookID;
    private javax.swing.JRadioButton rdbBookName;
    private javax.swing.JTable tblDisplay;
    private javax.swing.JTextField txtSearch;
    // End of variables declaration//GEN-END:variables
}
